name: Test on Multiple OS and Browsers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  browser-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        attempt: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        browser: [chrome-latest, firefox-latest, safari-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers (only if needed)
        if: contains(runner.os, 'Linux') || contains(runner.os, 'macOS')
        run: |
          if grep -q '@playwright/test' package.json; then
            npx playwright install --with-deps
          fi

      - name: Run tests
        run: |
          echo "Running attempt #${{ matrix.attempt }} on ${{ matrix.os }} with Node.js ${{ matrix['node-version'] }} and browser ${{ matrix.browser }}"

          if grep -q '@playwright/test' package.json; then
            npx playwright test --project=${{ matrix.browser }}
          elif grep -q 'cypress' package.json; then
            npx cypress run --browser ${{ matrix.browser }}
          elif grep -q 'karma' package.json; then
            npx karma start --browsers ${{ matrix.browser }}
          else
            echo "⚠️ No known test runner detected in package.json" && exit 1

