name: Test on Multiple OS and Browsers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  browser-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        attempt: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        browser: [chrome-latest, firefox-latest, safari-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}

      - name: Install dependencies
        run: npm ci

      - name: Testing on OS (${{ matrix.os }}) with Node.js (version ${{ matrix.node-version }}) attempt ${{ matrix.attempt }}
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          echo "Running tests on Node.js ${{ matrix.node-version }}, OS ${{ matrix.os }}, Browser ${{ matrix.browser }}"
          case "${{ matrix.browser }}" in
            chrome)
              npm run js-test-karma -- --browsers=ChromeHeadless
              ;;
            firefox)
              npm run js-test-karma -- --browsers=FirefoxHeadless
              ;;
            safari)
              if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                npm run js-test-karma -- --browsers=Safari
              else
                echo "Safari only runs on macOS or via BrowserStack"
              fi
              ;;
          esac
